version: '3.8'

services:
  server:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - '5000:5000'
    environment:
      - MONGO_URI=mongodb://mongo:27017
      - PORT=5000
      - JWT_SECRET=mybiggestsecretforurlshorner
    depends_on:
      - mongo
  mongo:
    image: mongo:latest
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
